name: Hello World
# Events
on:
  push:
    branches :
      - main
  pull_request :
    branches :
      - main
  workflow_dispatch :

# Workflow / Jobs

jobs:
  hello_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: echo "Hello World 1"
        shell: bash
  hello_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: echo "Hello World 2"
        shell: bash
